name: schedule_my_cut
description: "Schedule and cancel your barbershop appointments and view all of them being a barber owner."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  riverpod_lint: ^2.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
